# Alpha-sorted list
require "./hal/device"
require "./hal/device_drivers"
require "./hal/device_manager"
require "./hal/gdt"
require "./hal/idt"
require "./hal/keyboard"
require "./hal/keymaps"
require "./hal/pic"
require "./hal/pit"
require "./hal/portio"
